build:
    environment:
        php:
            version: 5.4
    tests:
        override:
            command: phpunit --coverage-clover=my-coverage-file
            coverage:
                file: my-coverage-file
                format: php-clover
